services:
  nginx:
    container_name: nginx
    image: nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
      - mariadb
    build: requirements/nginx
    ports:
      - "443:443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    build: requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build: requirements/wordpress
    restart: on-failure
    ports:
    - "8080:80"
    expose:
      - "9000"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cisse/data/wordpress

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cisse/data/mariadb

networks:
  inception:
    driver: bridge
