version: "3"

services:
  # nginx:
  #   container_name: nginx
  #   build: requirements/nginx
  #   ports:
  #     - "80:80"
  #   env_file:
  #     - .env
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
  # wordpress:
  #   container_name: wordpress
  #   build: requirements/wordpress
  #   ports:
  #     - "8080:80"
  #   env_file:
  #     - .env
